version: "2"

run:
  timeout: 3m

formatters:
  enable:
    - goimports

linters:
  enable:
    - asciicheck
    - bodyclose
    - canonicalheader
    - copyloopvar
    - durationcheck
    - dupword
    - errcheck
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - errname
    - nolintlint
    - nosprintfhostport
    - godot
    - whitespace
    - importas
    - usestdlibvars
    - thelper
    - tparallel
    - exhaustive
    - nilnil
    - fatcontext
    - gosec
    - sqlclosecheck
    - makezero
    - gocheckcompilerdirectives
    - perfsprint
    - promlinter
    - testifylint
    - sloglint
    - loggercheck
    - contextcheck
    - noctx
    - forcetypeassert
    - intrange
    - modernize
    - exptostd
    - usetesting
    - goconst
    - predeclared
    - recvcheck
    - err113
    - wrapcheck
    - nilnesserr
    - bidichk

  settings:
    revive:
      config: revive.toml
    godot:
      capital: true

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unparam
          - goconst
          - err113
          - wrapcheck
