version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/go
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - ../.env.example
    environment:
      - IMSUB_REDIS_URL=redis://default:@redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379"
